version: '3.8'

services:
  db:
    image: mysql
    container_name: db_symblog
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_symblog
    restart: always
    depends_on:
      - db

    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - dev

  www:
    build: docker
    container_name: www_symblog
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./docker/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
      - /var/www/project/vendor # ignore vendor map. This will prevent Docker from attempting to mount your entire Vendor directory (which is likely huge)
    networks:
      - dev

networks:
  dev:

volumes:
  db-data:
